name: CI Workflow

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  test: # Changed job name to 'test' for clarity
    name: Run Python tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Matches your project's Python version

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create and activate virtual environment
        run: |
          uv venv .ci-venv # Create a venv named .ci-venv
          source .ci-venv/bin/activate # Activate it

      - name: Install dependencies and project in editable mode (with test extras)
        # uv will now use the activated .ci-venv
        run: uv pip install -e ".[test]" 

      - name: Run tests with pytest
        # pytest will also use the Python from the activated .ci-venv
        run: pytest -v

  # You can keep other jobs here if you had them, or add them later.
  # For example, the 'do_nothing' job from earlier is now replaced by 'test'.
  # If you want a separate job for deployment later, you can add it.
