name: CI Workflow

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  test: # Changed job name to 'test' for clarity
    name: Run Python tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Matches your project's Python version

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH # Ensures 'uv' command is available
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies and run tests
        shell: bash # Explicitly use bash to ensure 'source' works as expected
        run: |
          uv venv .ci-venv # Create venv
          source .ci-venv/bin/activate # Activate it
          
          echo "--- Installing dependencies ---"
          uv pip install -e ".[test]" # Install in the activated venv
          
          echo "--- Running tests ---"
          pytest -v # Run pytest in the activated venv

  # You can keep other jobs here if you had them, or add them later.
  # For example, the 'do_nothing' job from earlier is now replaced by 'test'.
  # If you want a separate job for deployment later, you can add it.
